name = "MiscBenchmarks"
uuid = "a3609e63-ce08-44ae-b805-38c77477d81a"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[deps]
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
